const data = [
{"time":"10月10日","type":"交通","desp":"上班","cost":"2","more":""},
{"time":"10月10日","type":"交通","desp":"下班","cost":"2","more":""},
{"time":"10月10日","type":"饮食","desp":"午饭_快餐","cost":"19.5","more":""},
{"time":"10月10日","type":"信用卡还款","desp":"中信银行","cost":"200","more":"以后刷卡要三思"},
{"time":"10月11日","type":"交通","desp":"上班","cost":"2","more":""},
{"time":"10月11日","type":"饮食","desp":"早饭_面包","cost":"5.5","more":""},
{"time":"10月11日","type":"交通","desp":"中午超市来回","cost":"6","more":""},
{"time":"10月11日","type":"家居日用衣物","desp":"被子四件套","cost":"589","more":"生虫了, 没办法"},
{"time":"10月11日","type":"饮食","desp":"蒙牛一箱","cost":"67.2","more":""},
{"time":"10月11日","type":"饮食","desp":"衢州土菜","cost":"51","more":""},
{"time":"10月11日","type":"饮食","desp":"炒粉干","cost":"10.5","more":""},
{"time":"10月11日","type":"交通","desp":"下班","cost":"2","more":""},
{"time":"10月11日","type":"饮食","desp":"外卖炒饭","cost":"11.9","more":"饿了么"},
{"time":"10月11日","type":"家居日用衣物","desp":"内裤","cost":"69","more":"不只是吸引"},
{"time":"10月12日","type":"交通","desp":"上班","cost":"2","more":""},
{"time":"10月12日","type":"通讯","desp":"移动西安充值","cost":"100","more":""},
{"time":"10月12日","type":"饮食","desp":"午饭黄焖鸡","cost":"13.49","more":""},
{"time":"10月12日","type":"娱乐","desp":"爱奇艺vip","cost":"15","more":"自动续费"},
{"time":"10月12日","type":"交通","desp":"下班","cost":"2","more":""},
{"time":"10月12日","type":"饮食","desp":"晚饭衢州","cost":"34","more":""},
{"time":"10月13日","type":"饮食","desp":"农夫山泉","cost":"2","more":""},
{"time":"10月13日","type":"饮食","desp":"午饭牛肉汤","cost":"21","more":""},
{"time":"10月13日","type":"医药","desp":"营养品","cost":"546","more":""},
{"time":"10月13日","type":"家居日用衣物","desp":"香皂牙膏衣领净","cost":"81.3","more":""},
{"time":"10月13日","type":"饮食","desp":"酸奶","cost":"25.5","more":""},
{"time":"10月13日","type":"饮食","desp":"水果","cost":"16.43","more":""},
{"time":"10月13日","type":"饮食","desp":"MM豆","cost":"5.5","more":"不该买"},
{"time":"10月13日","type":"饮食","desp":"果醋","cost":"10","more":"不该买"},
{"time":"10月13日","type":"医药","desp":"999感冒","cost":"30","more":""},
{"time":"10月13日","type":"饮食","desp":"酸辣粉","cost":"28","more":""},
// {"time":"10月13日","type":"借出不算在支出","desp":"闫乐","cost":"2000","more":"不算支出"},
{"time":"10月14日","type":"饮食","desp":"午饭衢州","cost":"94","more":""},
{"time":"10月14日","type":"饮食","desp":"晚饭百香园","cost":"1.5","more":"退卡"},
{"time":"10月14日","type":"饮食","desp":"蘑菇青菜葱","cost":"13.32","more":""},
{"time":"10月15日","type":"交通","desp":"上班","cost":"2","more":""},
{"time":"10月15日","type":"饮食","desp":"午饭炒饭","cost":"16.59","more":""},
{"time":"10月15日","type":"饮食","desp":"晚饭黄焖鸡","cost":"14.6","more":""},
{"time":"10月16日","type":"交通","desp":"上班","cost":"2","more":""},
{"time":"10月16日","type":"饮食","desp":"早饭面包","cost":"5.5","more":""},
{"time":"10月16日","type":"交通","desp":"中午来回","cost":"4","more":""},
{"time":"10月16日","type":"饮食","desp":"百香园","cost":"22","more":""},
{"time":"10月16日","type":"饮食","desp":"晚饭纸包鸡","cost":"18","more":""},
{"time":"10月16日","type":"交通","desp":"加班打车","cost":"23","more":""},
{"time":"10月16日","type":"家居日用衣物","desp":"袜子*2","cost":"18","more":""},
{"time":"10月17日","type":"交通","desp":"上班","cost":"2","more":""},
{"time":"10月17日","type":"饮食","desp":"早饭面包","cost":"5.2","more":""},
{"time":"10月17日","type":"饮食","desp":"黄焖鸡","cost":"13.9","more":""},
{"time":"10月17日","type":"饮食","desp":"咖喱饭","cost":"19.59","more":""},
{"time":"10月17日","type":"交通","desp":"打车","cost":"17","more":""},
{"time":"10月18日","type":"交通","desp":"上班","cost":"","more":""},{"time":"10月18日","type":"饮食","desp":"面包酸奶","cost":"9.9","more":""},
{"time":"10月18日","type":"饮食","desp":"午饭便当","cost":"11.9","more":""},
{"time":"10月18日","type":"饮食","desp":"晚饭锅贴","cost":"19","more":""},
{"time":"10月18日","type":"交通","desp":"打车回家","cost":"21","more":""},
{"time":"10月18日","type":"医药","desp":"红花油","cost":"8.8","more":""},
{"time":"10月19日","type":"交通","desp":"上班","cost":"2","more":""},
{"time":"10月19日","type":"饮食","desp":"喜士多","cost":"10","more":""},
{"time":"10月19日","type":"饮食","desp":"黄焖鸡","cost":"18","more":""},
{"time":"10月19日","type":"请客或随份子","desp":"星巴克","cost":"75","more":""},
{"time":"10月19日","type":"交通","desp":"下班","cost":"2","more":""},
{"time":"10月19日","type":"饮食","desp":"花甲米线","cost":"15","more":""},
{"time":"10月20日","type":"请客或随份子","desp":"王星星结婚","cost":"500","more":""},
{"time":"10月20日","type":"交通","desp":"加班上下班","cost":"4","more":""},
{"time":"10月20日","type":"饮食","desp":"酸菜鱼*2","cost":"46","more":""},
{"time":"10月20日","type":"饮食","desp":"牛肉汤*2","cost":"24","more":""},
{"time":"10月21日","type":"交通","desp":"加班上下班","cost":"4","more":""},
{"time":"10月21日","type":"保险","desp":"中国平安","cost":"1114","more":""},
{"time":"10月21日","type":"饮食","desp":"黄焖鸡","cost":"18.1","more":""},
{"time":"10月21日","type":"饮食","desp":"炒粉干+蛋","cost":"11","more":""},
{"time":"10月21日","type":"通讯","desp":"杭州号充值","cost":"100","more":""},
{"time":"10月21日","type":"交通","desp":"去城西银泰","cost":"22","more":""},
{"time":"10月21日","type":"交通","desp":"回家","cost":"20","more":""},
{"time":"10月21日","type":"饮食","desp":"花甲米线*2","cost":"30","more":""},
{"time":"10月21日","type":"饮食","desp":"油炸串串","cost":"15","more":"不应该"},
{"time":"10月21日","type":"家居日用衣物","desp":"H&M","cost":"751","more":""},
{"time":"10月22日","type":"交通","desp":"上班","cost":"2","more":""},
{"time":"10月22日","type":"饮食","desp":"喜士多","cost":"9.9","more":""},
{"time":"10月22日","type":"饮食","desp":"纸包鸡","cost":"18","more":""},
{"time":"10月22日","type":"饮食","desp":"咖啡灌装2个","cost":"8","more":"提神*2"},
{"time":"10月22日","type":"交通","desp":"下班打车","cost":"18.5","more":""},
{"time":"10月22日","type":"饮食","desp":"安徽料理","cost":"18.5","more":"鸭头不该吃"},
{"time":"10月23日","type":"交通","desp":"上班","cost":"2","more":""},
{"time":"10月23日","type":"饮食","desp":"喜士多","cost":"9.9","more":""},
{"time":"10月23日","type":"饮食","desp":"快餐","cost":"22.5","more":""},
{"time":"10月23日","type":"信用卡还款","desp":"招商","cost":"130","more":""},
{"time":"10月23日","type":"饮食","desp":"咖啡","cost":"4","more":""},
{"time":"10月23日","type":"交通","desp":"下班","cost":"2","more":""},
{"time":"10月23日","type":"饮食","desp":"牛肉汤中份","cost":"17","more":""},
{"time":"10月23日","type":"饮食","desp":"海底捞等食物","cost":"68.8","more":"永辉"},
{"time":"10月23日","type":"医药","desp":"红糖","cost":"6.5","more":""},
{"time":"10月24日","type":"交通","desp":"上班","cost":"2","more":""},
{"time":"10月24日","type":"饮食","desp":"臊子面","cost":"15","more":""},
{"time":"10月24日","type":"饮食","desp":"咖啡","cost":"4","more":""},
{"time":"10月24日","type":"交通","desp":"下班","cost":"2","more":""},
{"time":"10月24日","type":"饮食","desp":"买水","cost":"4","more":"太渴了"},
{"time":"10月24日","type":"饮食","desp":"晚饭衢州","cost":"69","more":""},
{"time":"10月25日","type":"交通","desp":"上班","cost":"2","more":""},
{"time":"10月25日","type":"饮食","desp":"喜士多","cost":"8.8","more":""},
{"time":"10月25日","type":"饮食","desp":"芝士奶茶","cost":"22","more":"馋了"},
{"time":"10月25日","type":"饮食","desp":"油泼面","cost":"13","more":""},
{"time":"10月25日","type":"交通","desp":"打车回家","cost":"20","more":""},
{"time":"10月26日","type":"交通","desp":"上班","cost":"2","more":""},
{"time":"10月26日","type":"饮食","desp":"喜士多","cost":"9.9","more":""},
{"time":"10月26日","type":"饮食","desp":"顺旺基快餐","cost":"39","more":"两人"},
{"time":"10月26日","type":"交通","desp":"中午来回","cost":"4","more":""},
{"time":"10月26日","type":"饮食","desp":"咖啡","cost":"4","more":""},
{"time":"10月26日","type":"交通","desp":"打车","cost":"18","more":""},
{"time":"10月27日","type":"饮食","desp":"米","cost":"3.6","more":""},
{"time":"10月27日","type":"饮食","desp":"青菜豆腐笋山药","cost":"11.2","more":""},
{"time":"10月27日","type":"饮食","desp":"豆瓣酱","cost":"14","more":""},
{"time":"10月27日","type":"交通","desp":"加班","cost":"2","more":""},
{"time":"10月27日","type":"饮食","desp":"面","cost":"34","more":""},
{"time":"10月27日","type":"交通","desp":"打车","cost":"19","more":""},
{"time":"10月28日","type":"饮食","desp":"衢州","cost":"55","more":""},
{"time":"10月28日","type":"交通","desp":"加班","cost":"4","more":""},
{"time":"10月28日","type":"饮食","desp":"饮料","cost":"3","more":""},
{"time":"10月28日","type":"支付宝还款","desp":"借呗","cost":"475","more":""},
{"time":"10月28日","type":"饮食","desp":"金龙鱼","cost":"40","more":""},
{"time":"10月28日","type":"饮食","desp":"鸡排","cost":"12","more":"不该吃"},
{"time":"10月28日","type":"饮食","desp":"杂粮饼","cost":"5","more":""},
{"time":"10月28日","type":"饮食","desp":"牛肉粉","cost":"15","more":""},
{"time":"10月29日","type":"交通","desp":"","cost":"2","more":""},
{"time":"10月29日","type":"饮食","desp":"","cost":"9.9","more":""},
{"time":"10月29日","type":"饮食","desp":"牛肉汤","cost":"24","more":""},
{"time":"10月29日","type":"饮食","desp":"买菜","cost":"19.5","more":""},
{"time":"10月29日","type":"饮食","desp":"大桶水","cost":"10","more":""},
{"time":"10月29日","type":"交通","desp":"下班","cost":"2","more":""},
{"time":"10月30日","type":"交通","desp":"","cost":"2","more":""},{"time":"10月30日","type":"饮食","desp":"纸包鸡","cost":"18","more":""},
{"time":"10月30日","type":"交通","desp":"hello单车","cost":"1","more":""},
{"time":"10月30日","type":"饮食","desp":"全家买水","cost":"6","more":""},
{"time":"10月30日","type":"饮食","desp":"咖啡","cost":"4","more":""},
{"time":"10月30日","type":"饮食","desp":"牛肉粉","cost":"31.22","more":""},
{"time":"10月30日","type":"饮食","desp":"水果","cost":"26","more":""},
{"time":"10月31日","type":"交通","desp":"上班","cost":"2","more":""},
{"time":"10月31日","type":"饮食","desp":"喜士多","cost":"10.8","more":""},
{"time":"10月31日","type":"饮食","desp":"酸菜鱼","cost":"20","more":""},
{"time":"10月31日","type":"饮食","desp":"咖啡","cost":"8","more":""},
{"time":"10月31日","type":"交通","desp":"下班","cost":"21","more":""},
{"time":"11月1日","type":"交通","desp":"上班","cost":"2","more":""},
{"time":"11月1日","type":"饮食","desp":"喜士多","cost":"11.5","more":""},
{"time":"11月1日","type":"饮食","desp":"酸菜鱼*2","cost":"42","more":""},
{"time":"11月1日","type":"交通","desp":"中午来回","cost":"4","more":""},
{"time":"11月1日","type":"饮食","desp":"咖啡","cost":"4","more":""},
{"time":"11月1日","type":"房租","desp":"","cost":"4280","more":"痛心"},
{"time":"11月1日","type":"交通","desp":"打车回家","cost":"19","more":""},
{"time":"11月2日","type":"交通","desp":"上班","cost":"2","more":""},
{"time":"11月2日","type":"饮食","desp":"牛肉粉","cost":"18","more":""},
{"time":"11月2日","type":"饮食","desp":"锅贴","cost":"28","more":""},
{"time":"11月2日","type":"交通","desp":"打车回家","cost":"20","more":""},
{"time":"11月3日","type":"饮食","desp":"杂粮煎饼","cost":"12","more":""},
{"time":"11月3日","type":"饮食","desp":"买菜","cost":"20","more":""},
{"time":"11月3日","type":"饮食","desp":"乌鸡","cost":"23","more":""},
{"time":"11月3日","type":"饮食","desp":"鱼豆腐等","cost":"10","more":""},
{"time":"11月3日","type":"饮食","desp":"馒头","cost":"2","more":""},
{"time":"11月4日","type":"信用卡还款","desp":"JD白条","cost":"322","more":""},
{"time":"11月4日","type":"饮食","desp":"牛肉汤","cost":"24","more":""},
{"time":"11月4日","type":"交通","desp":"城西银泰退货","cost":"23","more":""},
{"time":"11月4日","type":"饮食","desp":"棒棒鸡","cost":"46","more":"贵又难吃"},
{"time":"11月4日","type":"饮食","desp":"寿司","cost":"42","more":""},
{"time":"11月4日","type":"饮食","desp":"喜士多","cost":"10","more":""},
{"time":"11月4日","type":"饮食","desp":"大麻花","cost":"25","more":""},
{"time":"11月4日","type":"交通","desp":"回家","cost":"4","more":""},
{"time":"11月5日","type":"交通","desp":"上班","cost":"2","more":""},
{"time":"11月5日","type":"饮食","desp":"喜士多","cost":"9.9","more":""},
{"time":"11月5日","type":"饮食","desp":"纸包鸡","cost":"17","more":""},
{"time":"11月5日","type":"信用卡还款","desp":"中信银行","cost":"135","more":""},
{"time":"11月5日","type":"交通","desp":"上班","cost":"2","more":""},
{"time":"11月5日","type":"饮食","desp":"","cost":"11","more":""},
{"time":"11月6日","type":"交通","desp":"去医院来回","cost":"8","more":""},
{"time":"11月6日","type":"医药","desp":"挂号","cost":"30","more":""},
{"time":"11月6日","type":"医药","desp":"媳妇药钱","cost":"254","more":""},
{"time":"11月6日","type":"饮食","desp":"","cost":"8","more":""},
{"time":"11月6日","type":"饮食","desp":"面","cost":"38","more":""},
{"time":"11月6日","type":"饮食","desp":"面包","cost":"10","more":""},
{"time":"11月6日","type":"家居日用衣物","desp":"","cost":"20","more":""},
{"time":"11月6日","type":"娱乐","desp":"钱王祠观菊","cost":"30","more":""},
{"time":"11月6日","type":"饮食","desp":"","cost":"30","more":""},
{"time":"11月6日","type":"饮食","desp":"","cost":"15","more":""},
{"time":"11月7日","type":"交通","desp":"上班","cost":"2","more":""},
{"time":"11月7日","type":"饮食","desp":"喜士多","cost":"10.9","more":""},
{"time":"11月7日","type":"饮食","desp":"快餐","cost":"12.5","more":""},
{"time":"11月7日","type":"饮食","desp":"喜士多","cost":"5.5","more":"多了"},
{"time":"11月7日","type":"请客或随份子","desp":"吃水果","cost":"220","more":"豪气干云"},
{"time":"11月8日","type":"交通","desp":"上班","cost":"2","more":""},
{"time":"11月8日","type":"饮食","desp":"纸包鸡","cost":"17","more":""},
{"time":"11月8日","type":"饮食","desp":"快餐","cost":"14","more":""},
{"time":"11月8日","type":"交通","desp":"下班","cost":"2","more":""},
{"time":"11月8日","type":"通讯","desp":"手机充值","cost":"100","more":""},
{"time":"11月8日","type":"学习资料","desp":"慕课","cost":"493","more":"头脑不冷静"},
{"time":"11月9日","type":"娱乐","desp":"网盘","cost":"144","more":""},
{"time":"11月9日","type":"支付宝还款","desp":"花呗","cost":"353.6","more":""},
{"time":"11月9日","type":"饮食","desp":"芭比馒头","cost":"5.5","more":""},
{"time":"11月9日","type":"交通","desp":"下班打车","cost":"19","more":""},
{"time":"11月10日","type":"饮食","desp":"衢州","cost":"76","more":""},
{"time":"11月10日","type":"饮食","desp":"零食","cost":"15.5","more":""},
{"time":"11月10日","type":"饮食","desp":"津市牛肉粉","cost":"18","more":""},
{"time":"11月10日","type":"饮食","desp":"油条豆浆","cost":"10","more":""}
]

const resMap = {};

let total = 0;

data.forEach(item => {
	// const tempTotal = 0;
	const type = item.type;
	let nowSpend = resMap[type]?resMap[type]:0;
	resMap[type] = nowSpend + Number(item.cost);

	total += Number(item.cost)
});

console.log('resMap is : ', resMap);
console.log('total is : ', total);

/**

resMap is :  { '交通': 383.5,
  '饮食': 2160.44,
  '信用卡还款': 787,
  '家居日用衣物': 1528.3,
  '通讯': 300,
  '娱乐': 189,
  '医药': 875.3,
  '借出不算在支出': 2000,
  '请客或随份子': 795,
  '保险': 1114,
  '支付宝还款': 828.6,
  '房租': 4280,
  '学习资料': 493 }
total is :  15734.139999999998

*/